# Generated by Django 3.2.2 on 2021-06-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='memories/%Y/%m/%d')),
            ],
        ),
    ]
